### PR TITLE
Remove use of deprecated scikit-learn functions

### PR DESCRIPTION
**Pull request by kwohlfahrt**
The number of deprecation warnings shown was getting a little insane (see issue #198). Touched quite a lot of things trying to get tests passing again, so a rough summary is:

Main changes:
- Use `np.random.multivariate_normal` instead of `sample_gaussian`
  - Factor out `fill_covars` to make this work for both Gausian/GMM HMMs
- Create a local copy of `log_multivariate_normal_density`

Other things touched in the process:
- delete old GMMHMM tests. They don't pass since the GMMHMM rewrite
- Fix a bug (I think?) in generating spherical covars for the test, looked like the shape was wrong?
- Clean up generation of covars in test of Gaussian HMM.

I'm not very familiar with this codebase, so please take a close look!

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
Only Python 2.6 is failing on travis, due to `np.broadcast_to` not existing. Numpy 1.10, which has `broadcast_to` should be available for python 2.6, so it must be a problem with conda.

Why not just use pip on travis?

**Comment by superbobry** [comment]
Hi Kai, thanks for your contribution! I am not sure about removing GMMHMM tests in the same PR. I know they've been failing, but I'd prefer to target them separately. Could you rebase?

We are not using pip, because at the time I did the CI infrastructure NumPy/SciPy were not shipping binary wheels and compilation took too much time.

**Comment by kwohlfahrt** [comment]
Sure, should I mark them xfail? I can change Travis to use pip, and that should get CI working again? Can split that up into separate PRs?

**Comment by superbobry** [comment]
Thanks, this looks good!

**Pull request merged**
